version: '3.8'
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-prisma
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: